# Laval University work team

<a href="https://www.bio.ulaval.ca/departement-et-professeurs/professeurs-et-personnel/professeurs/fiche/show/archambault-philippe/" target="_blank">Philippe Archambault</a>
will be the project manager. With a PhD in biology (1998), he began as a researcher at Fisheries and Oceans Canada (2000–2007) before becoming a professor at the Institut des sciences de la mer of the University of Quebec at Rimouski (2007–2017). Since 2017, he has been a professor at Laval University. Combining fundamental and theoretical research, Philippe has been studying the effects of various disturbances (of natural and human origin) on ecosystems for over 20 years. He has co-led or participated in many research programs focused on benthic biodiversity in Canada and abroad. The findings of his work have been used to develop protected marine areas, among others. He has also either authored or co-authored over 120 peer-reviewed scientific articles.

<a href="http://chone2.ca/people/david-beauchesne/" target="_black">David Beauchesne</a>
 is the post-doctoral student approached to carry out this project. With the experience he gained during his doctoral studies, David has all the qualifications required to carry out the work on the cumulative effects of marine activities.

Cindy Grant is a research professional on the Laval University team. Her diverse scientific and project management experience will be a major asset at all stages of the project leading to the assessment of the cumulative effects of marine activities.

An undergraduate student could take part in this project as a research assistant. This research assistant could be hired full-time during the summer or part-time during the school year. The candidate will be required to have geographical information system and programming experience.
