# Data collection and management

Data will be collected in cooperation with various project collaborators and with the support of Transport Canada and members of the project led by the St. Lawrence Action Plan. No new data will be collected for this assessment. The entire study therefore relies on the availability of data that can be used to characterize the spatial distribution of valued components and stressors, as well as the vulnerability of valued components to stressors. Special attention will be paid to knowledge possessed by Indigenous and non-Indigenous communities. In that respect, we are planning meetings with First Nations representatives following the presentation of the methodological approach in order to put in place an appropriate strategy that will enable us to build on their knowledge and incorporate their concerns. The work approach adopted will result in an iterative, transparent process in which new considerations can be incorporated or previously shared considerations can be adjusted further to an engagement process. It should be noted that the concerns of First Nations, coastal communities and various project stakeholders were also considered ahead of this study through various engagement sessions organized by the Transport Canada team.

Databases will be managed by the Laval University work team with the aim of ensuring full transparency in the work carried out. To the extent possible, our team plans to fully share the code and data used for all steps in the cumulative effects assessment. Sensitive data could still be embargoed or be subject to stricter sharing agreements limiting or fully blocking access to some types of data. Nevertheless, this type of data can be incorporated into an open process through proper cataloguing so that a user can have an inkling as to the type and origin of the data used in the analyses as well as the relevant contacts for obtaining more information on the data. All suggestions, recommendations and requests from various partners as to the collection, management and sharing of data will be considered to ensure effective and respectful cooperation.

In addition to the meetings and engagement sessions planned in the contract seeking close cooperation with Transport Canada officials, we will adopt a transparent, replicable approach similar to the one we use for our initiative to characterize stressors in the Estuary and Gulf of St. Lawrence called
<a href="https://david-beauchesne.shinyapps.io/edriversapp/" target="_blank"><i>eDrivers</i></a>.
We are basing our approach on the
<a href="https://ogsl.ca/fr/principes-fair" target="_blank"><i>FAIR</i></a>
Data Principles, the purpose of which is to ensure that the data used are findable, accessible, interoperable and reusable.
We are therefore using programming tools, including
<a href="https://www.r-project.org/" target="_blank"><i>R</i></a>
language.[^r] The use of programming tools, like software such as
<a href="https://www.arcgis.com/index.html" target="_blank"><i>ArcGIS</i></a>[^arc], offers a number of advantages. These tools provide a great deal of flexibility in incorporating changes or new considerations very quickly without having to repeat multiple steps in a complex process. This flexibility is not limited to analyses, since all steps in a project, from the integration of raw data to the production of reports, can be integrated and thus easily modified. It then becomes easy to add comments or new recommendations following engagement sessions, for example. We will also use
<a href="https://github.com/" target="_blank"><i>GitHub</i></a>[^git],
a version control tool that allows for documentation, quality control, and development and modification tracking of relevant programming elements for the entire project.


[^r]: R est un logiciel libre destiné aux statistiques, la science des données et les graphiques (https://www.r-project.org/)
[^arc]: ArcGIS est une suite de logiciels d'information géographique (SIG) développés par la société américaine Esri (https://www.arcgis.com/index.html)
[^git]: GitHub est un service web d'hébergement et de gestion de développement de logiciels utilisé par plus de 40 millions d'utilisateurs partout à travers le monde (https://github.com/).
