# Schedule

| Deliverable | Date |
| :------------------------------- | :------------- |
| Launch and preparation of schedule and work  | Early February 2020 |
| Document containing an overview of the method	| May 2020 |
| Creation of list of data needs and initiation of contact to obtain the necessary data	| Mid-March – June 2020 |
| Webinar with partners and collaborators | June 2020 |
| Adjustment to approach based on collaborator comments | May – June 2020 |
| Contacts and data collection | June 2020 – March 2021 |
| Mapping of stressors and valued components | June 2020 – March 2021 |
| Preliminary assessment of cumulative exposure of valued components to environmental stressors	| November 2020 – February 2021 |
| Preliminary assessment of vulnerabilities of valued components | November 2020 – February 2021 |
| Summary report and presentation of preliminary findings for comment during a workshop, review and discussions on the vulnerability of valued components, and discussions on mapping of sources of stress and valued components | March 2021 |
| Adjustment to approach based on collaborator comments, integration of new considerations and incorporation of knowledge from collaborators and all participants involved in the project to assess the vulnerability of valued components | April – May 2021 |
| Contacts and collection of missing data or data proposed during March 2021 workshop	| April – May 2021 |
| Final analyses and preparation of report | May 2021 – December 2021 |
| Delivery of final report for translation and distribution	|	December 31, 2021 |
| Presentation of final report at a workshop	| Early February 2022 |
